[package]
name = "dilib-derive"
version = "0.1.0"
authors = ["Freddy L."]
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.73" , features=["parsing"]}
mattro = "0.1.2"

[dev-dependencies]
dilib = { path="../dilib" }
