[package]
name = "dilib"
version = "0.1.0-alpha"
authors = ["Freddy L."]
edition = "2021"

[features]
derive = ["dilib-derive"]

[dependencies]
dilib-derive = { path = "../dilib-derive", optional = true }