[package]
name = "dilib"
description = "A dependency injection library for Rust"
keywords = ["rust-patterns"]
version = "0.1.3-alpha"
authors = ["Freddy L."]
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Neo-Ciber94/dilib-rs/"
homepage = "https://crates.io/crates/dilib/"
documentation = "https://docs.rs/dilib/"

[features]
full = ["derive", "global"]
derive = ["dilib-derive"]
global = []
#unstable_provide = ["dilib-macros", "global", "ctor", "once_cell"]
unstable_provide = ["dilib-macros", "global", "ctor"]

[dependencies]
dilib-derive = { version="0.1.0-alpha", optional = true }
dilib-macros = { path = "../dilib-macros", optional = true}
ctor = { version ="0.1.22", optional = true }
#once_cell = { version = "1.10.0", optional = true }
once_cell = "1.10.0"