[package]
name = "global"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dilib = { path = "../../dilib", features = ["full"]}
ctor = "0.1.22"
once_cell = "1.10.0"