[package]
name = "test_suite"
version = "0.1.0"
authors = ["Freddy L."]
edition = "2018"
publish = false

[dependencies]
dilib = { path = "../dilib", features=["derive", "unstable_provide"] }

[dev-dependencies]
macrotest = "1.0.8"
trybuild = { version = "1.0.59", features = ["diff"] }
