[package]
name = "web_api"
version = "0.1.0"
edition = "2021"

[dependencies]
dilib = { path = "../../dilib", features=["derive"] }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
env_logger = "0.9.0"